#!/usr/bin/env bash
set -Eeuo pipefail
set -x

# Repack gitlab-runner without its dependency on the huge
# gitlab-runner-helper-images, only needed by the docker/k8s executors.

VERSION="${1:-latest}"
[[ $VERSION == "latest" ]] || VERSION="v${VERSION#v}"

wget -O gitlab-runner.deb "https://gitlab-runner-downloads.s3.amazonaws.com/$VERSION/deb/gitlab-runner_amd64.deb"

rm -rf gitlab_runner
mkdir gitlab_runner
pushd gitlab_runner

ar x ../gitlab-runner.deb

gzip -d control.tar.gz
tar -xf control.tar ./control
sed -i 's/gitlab-runner-helper-images[^,]*, //' control
tar -uf control.tar ./control
gzip control.tar

ar rcv ../gitlab-runner-light.deb debian-binary control.tar.gz data.tar.bz2

popd
rm -rf gitlab_runner
